import React from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ImageBackground, ScrollView } from 'react-native';

const PrivacyPolicyScreen = ({ navigation }) => {
    // Privacy policy text
    const privacyPolicyText = `
Welcome to Galactic Stories! Your privacy is critically important to us. Galactic Stories, accessible from galacticstories.com, is dedicated to respecting the privacy of your personal information and data. This privacy policy document describes in detail the types of personal information collected and recorded by our app and how we use it.

1. Information We Collect and How We Use It:
- Identity Data: Includes your age and gender. This is used to personalize the content generated by the app.
- Preferences: Includes story themes and special characters you provide (optional). This helps tailor the story generated to your interests.
- Voice Data: Utilizes Apple's voice (com.apple.ttsbundle.siri_Nicky_en-US_compact) through expo-speech API for reading stories out loud.

We utilize this data to process and respond to your requests for story generation using the OpenAI API. The stories are created based on the inputs you provide, and no personal data is stored after the story generation process is complete.

2. Data Security:
Galactic Stories is committed to ensuring that your information is secure. In order to prevent unauthorized access or disclosure, we have put in place suitable physical, electronic, and managerial procedures to safeguard and secure the information we collect online. However, please note that no method of transmission over the internet or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.

3. Data Sharing and Disclosure:
We do not sell, trade, or rent users' personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates, and advertisers for the purposes outlined above.

4. Third-party Services:
The only third-party service provider used by Galactic Stories is OpenAI for story generation purposes. We send the user-provided data to OpenAI's ChatGPT 3.5 API, which then processes this information to generate stories. We do not store any of your data post the generation of stories.

5. Your Consent:
By using our app, you hereby consent to our privacy policy and agree to its terms.

6. Changes to This Privacy Policy:
We may update our Privacy Policy from time to time. Thus, we advise you to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page.

7. Contact Us:
For any questions or suggestions about our Privacy Policy, do not hesitate to contact us at info@galacticstories.com.

Disclaimer:
The Galactic Stories app is provided on an "as is" and "as available" basis without any warranties of any kind, including that the app will operate error-free or that the app, its servers, or the content are free of computer viruses or similar contamination or destructive features. We disclaim all licenses to the fullest extent permitted by law, whether express or implied, including the implied licenses of merchantability, fitness for a particular purpose, title, and non-infringement.
`;

    return (
        <ImageBackground source={require('./assets/welcome.jpg')} style={styles.backgroundImage}>
            <View style={styles.container}>
                <View style={styles.storyContainer}>
                    <ScrollView style={styles.scrollView}>
                        <Text style={styles.storyText}>{privacyPolicyText}</Text>
                    </ScrollView>
                </View>

                <TouchableOpacity style={styles.button} onPress={() => navigation.navigate('Home')}>
                    <Text style={styles.buttonText}>Go back</Text>
                </TouchableOpacity>
            </View>
        </ImageBackground>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
    },
    storyContainer: {
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        borderRadius: 20,
        padding: 20,
        marginTop: 60,
        width: '90%',
        minHeight: '60%',
        maxHeight: '80%', // Set a maximum height
    },
    scrollView: {
        // Additional styles if needed for the scroll view
    },
    storyText: {
        fontFamily: 'Montserrat',
        fontSize: 18,
        color: 'black',
        textAlign: 'justify',
    },
    button: {
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        padding: 15,
        paddingHorizontal: 30,
        borderRadius: 25,
    },
    buttonText: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
        fontFamily: 'Montserrat',
        textAlign: 'center',

    },
    backgroundImage: {
        flex: 1,
        resizeMode: 'cover',
        justifyContent: 'center',
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: 10,
    },


});

export default PrivacyPolicyScreen;